### ISSUE TITLE
Nut addon absent in community addons

### ISSUE THREAD

**Issue by pauldogg** [hassio-addons/addon-nut#10] opened 2019-10-04 20:40 UTC
# Problem/Motivation
unable to install nut add-on
> (Why the issue was filed)

## Expected behavior
appearance of NUT add-on in add-on store
> (What you expected to happen)

## Actual behavior
addon does not populate in add-on store when the repository is added to the community addon-on 
> (What actually happened)
nothing
## Steps to reproduce
add https://github.com/hassio-addons/repository to community add-on as indicated in the instructions
> (How can someone else make/see it happen)
add https://github.com/hassio-addons/repository to community add-on as indicated in the instructions
## Proposed changes
add NUT add-on to the community add-ons
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
the instructions on the addon webpage, are not working

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment] 2019-10-04 20:50
This add-on is not ready for production.

**Comment by sinclairpaul** [comment] 2019-10-04 20:50
Duplicate of:
https://github.com/hassio-addons/repository/issues/113
#3 

The addon is yet to be released.

**Closed** 2019-10-04 20:50 UTC
