### ISSUE TITLE
Not supported in NUT 2.7.4, for work need NUT 2.8.0

### ISSUE THREAD

**Issue by SandDeath** [hassio-addons/addon-nut#283] opened 2023-03-14 19:05 UTC
# Problem/Motivation

NAT setup cannot find CMU-SP1200IEC, according to the documentation on the website https://networkupstools.org / this model is supported

## Expected behavior

The UPS to be recognized and monitored

## Actual behavior

Fails on starting the driver

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 43631cf
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.3.4
 Home Assistant Supervisor: 2023.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[21:58:17] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[21:58:17] INFO: Setting mode to netserver...
[21:58:17] INFO: Connected USB devices:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 004: ID 0001:0000 Fry's Electronics MEC0003
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[21:58:17] INFO: Generating /etc/nut/upsd.users...
[21:58:17] INFO: Configuring user: sand_death
[21:58:17] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[21:58:18] INFO: Configuring Device named Server_UPS...
[21:58:18] INFO: Starting the UPS drivers...
Network UPS Tools - Generic Q* USB/Serial driver 0.28 (2.7.4)
USB communication driver 0.33
Fatal error: 'noscanlangid' is not a valid flag for this driver.
Look in the man page or call this driver with -h for a list of
valid variable names and flags.
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 0
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun upsd (no readiness notification)
services-up: info: copying legacy longrun upsmon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[21:58:18] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000282	listening on 0.0.0.0 port 3493
   0.000499	Can't connect to UPS [Server_UPS] (nutdrv_qx-Server_UPS): No such file or directory
[21:58:18] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000252	Using power down flag file /etc/killpower
   0.000421	UPS: Server_UPS@localhost (master) (power value 1)
   0.000489	debug level is '1'
   0.000498	Warning: running as one big root process by request (upsmon -p)
   0.000746	Init SSL without certificate database
   0.002623	Trying to connect to UPS [Server_UPS@localhost]
   0.514611	User upsmonmaster@127.0.0.1 logged into UPS [Server_UPS]
   0.003430	Logged into UPS Server_UPS@localhost
   0.003541	Poll UPS [Server_UPS@localhost] failed - Driver not connected
{"message":"Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
```

## Steps to reproduce

Connect the UPS (USB cable) and configure NUT like

```
users:
  - actions: []
    instcmds:
      - all
    password: Fylhtq_Rjhjktd1994
    username: sand_death
devices:
  - driver: nutdrv_qx
    name: Server_UPS
    port: auto
    config:
      - vendorID = "0001"
      - productID = "0000"
      - protocol = "hunnox"
      - langid_fix = "0x0409"
      - novendor
      - noscanlangid
mode: netserver
shutdown_host: "false"
list_usb_devices: true

```

## Proposed changes

Update the addon version to NUT version 2.8.0

**Comment by frenck** [comment] 2023-03-14 19:15
> Update the addon version to NUT version 2.8.0

We can't. Debian doesn't have it.

Closing the issue as it is a feature request, not a bug.

../Frenck

**Closed by frenck** 2023-03-14 19:15 UTC
