### ISSUE TITLE
add on not listed in the repository 

### ISSUE THREAD

**Issue by haddood** [hassio-addons/addon-nut#11] opened 2019-11-06 17:09 UTC
# Problem/Motivation

> the add on in listed in https://github.com/hassio-addons/repository. thus can't be found

## Expected behavior

> the add on is listed in https://github.com/hassio-addons/repository

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by sinclairpaul** [comment] 2019-11-06 17:25
Duplicate of:
#10 
#3

The addon is yet to be released.

**Closed by sinclairpaul** 2019-11-06 17:25 UTC
